// The link helpers behind "right-click → Open link in new tab".
//
// Two halves have to stay true together, and they pull against each other:
//
// 1. An in-app link must carry a real `href`, or the browser has no URL to offer
//    on right-click, ⌘-click or middle-click.
// 2. A plain left click must be cancelled, or the browser follows that href and
//    reloads the whole app instead of transitioning between screens.
//
// Cancel too much and (1) is dead — every modified click gets swallowed and no
// new tab ever opens, which is exactly the bug this shipped to fix. Cancel too
// little and (2) breaks. The cases below pin the line between them.
//
// Every href here is generated by `routePath`, which shares its route → path
// switch with the address bar (`pathForRoute` in navigation/webRoutes.ts), so
// these also pin that a link's URL matches the URL the router lands on.

import { describe, expect, it, vi } from 'vitest';
import type { GestureResponderEvent } from 'react-native';

import { externalLinkProps, linkProps, pressInsideLink, routePath } from '../links';

/** A click event shaped like the one react-native-web hands to `onPress` on web. */
function clickEvent(modifiers: Record<string, boolean | number> = {}) {
  return {
    metaKey: false,
    ctrlKey: false,
    shiftKey: false,
    altKey: false,
    button: 0,
    preventDefault: vi.fn(),
    stopPropagation: vi.fn(),
    ...modifiers,
  };
}

function press(props: { onPress?: (event: GestureResponderEvent) => void }, event: object) {
  props.onPress?.(event as unknown as GestureResponderEvent);
}

describe('routePath builds the URL the router will land on', () => {
  it('covers the destinations screens link to', () => {
    expect(routePath.home()).toBe('/');
    expect(routePath.bills()).toBe('/bills');
    expect(routePath.legislators()).toBe('/legislators');
    expect(routePath.privacy()).toBe('/privacy');
    expect(routePath.terms()).toBe('/terms');
    expect(routePath.bill('94-2025-SF334')).toBe('/bills/94-2025-SF334');
    expect(routePath.legislator('abc-123')).toBe('/legislators/abc-123');
    expect(routePath.findMyLegislator()).toBe('/find-my-legislator');
  });

  it('carries a bill tab and an ask question as query params', () => {
    expect(routePath.bill('94-2025-SF334', { tab: 'votes' })).toBe(
      '/bills/94-2025-SF334?tab=votes',
    );
    expect(routePath.ask({ q: 'who voted yes' })).toBe('/ask?q=who+voted+yes');
    expect(routePath.ask()).toBe('/ask');
  });

  it('escapes an id so a link can never produce a malformed URL', () => {
    expect(routePath.bill('a b/c')).toBe('/bills/a%20b%2Fc');
    expect(routePath.legislator('a b/c')).toBe('/legislators/a%20b%2Fc');
  });
});

describe('linkProps gives an in-app destination a real href', () => {
  it('exposes the URL and marks the element as a link', () => {
    const props = linkProps(routePath.bills());
    expect(props.href).toBe('/bills');
    expect(props.accessibilityRole).toBe('link');
  });

  it('handles a plain left click itself, so the page does not reload', () => {
    const navigate = vi.fn();
    const event = clickEvent();
    press(linkProps('/bills', navigate), event);
    expect(event.preventDefault).toHaveBeenCalledOnce();
    expect(navigate).toHaveBeenCalledOnce();
  });

  it.each([
    ['meta (⌘-click — new tab)', { metaKey: true }],
    ['ctrl (Windows/Linux new tab)', { ctrlKey: true }],
    ['shift (new window)', { shiftKey: true }],
    ['alt (download)', { altKey: true }],
    ['a non-primary mouse button', { button: 1 }],
  ])('leaves a %s click to the browser', (_label, modifier) => {
    const navigate = vi.fn();
    const event = clickEvent(modifier);
    press(linkProps('/bills', navigate), event);
    expect(event.preventDefault).not.toHaveBeenCalled();
    expect(navigate).not.toHaveBeenCalled();
  });
});

describe('externalLinkProps sends an official source to a new tab', () => {
  const url = 'https://www.revisor.mn.gov/bills/94/2026/0/HF/4138/';

  it('renders as an anchor the browser opens itself', () => {
    const props = externalLinkProps(url);
    expect(props.href).toBe(url);
    expect(props.hrefAttrs).toEqual({ target: '_blank', rel: 'noopener noreferrer' });
  });

  it('drops the handler on web, so one click cannot open two tabs', () => {
    // The native fallback (Linking.openURL) is passed in and deliberately ignored
    // here: on web the anchor's own target="_blank" does the opening.
    expect(externalLinkProps(url, vi.fn()).onPress).toBeUndefined();
  });
});

describe('pressInsideLink keeps a control inside a link from firing that link', () => {
  it('cancels the click as well as stopping it propagating', () => {
    // stopPropagation alone leaves the browser's default action intact, and inside
    // an anchor that action is "follow that anchor's URL" — so the control would
    // run AND the card's page would load over the top of it.
    const act = vi.fn();
    const event = clickEvent();
    pressInsideLink(act)(event as unknown as GestureResponderEvent);
    expect(event.preventDefault).toHaveBeenCalledOnce();
    expect(event.stopPropagation).toHaveBeenCalledOnce();
    expect(act).toHaveBeenCalledOnce();
  });

  it('still swallows the click when the control does nothing (the inert Track button)', () => {
    const event = clickEvent();
    pressInsideLink()(event as unknown as GestureResponderEvent);
    expect(event.preventDefault).toHaveBeenCalledOnce();
    expect(event.stopPropagation).toHaveBeenCalledOnce();
  });

  it('cancels a modified click too, rather than opening the wrong URL in a new tab', () => {
    // ⌘-click here would open the SURROUNDING card's URL, not the one the person
    // clicked. Right place in this tab beats wrong place in a new one (issue #760).
    const act = vi.fn();
    const event = clickEvent({ metaKey: true });
    pressInsideLink(act)(event as unknown as GestureResponderEvent);
    expect(event.preventDefault).toHaveBeenCalledOnce();
    expect(act).toHaveBeenCalledOnce();
  });
});
