"""Store each campaign finance download as a dated snapshot, published as a whole set.

Net: campaign finance is the one source that replaces whole sets instead of updating
rows, because Minnesota publishes no per-transaction identifier and two payments can be
legitimately identical, so no key built from a row's contents can tell a genuine repeat
payment from a re-import. These 5 tables hold a downloaded file, where its bytes live,
every fetch attempt, the set of 3 files published together, and a pointer to the live
set. Design: docs/architecture/campaign-finance-system-design.md (#1328).

Additive only. Every table is new and nothing existing is touched, so the downgrade is a
clean drop.

Revision ID: 0029_campaign_finance_snapshots
Revises: 0028_legislator_committee_link
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0029_campaign_finance_snapshots"
down_revision = "0028_legislator_committee_link"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cf_snapshot",
        sa.Column(
            "dataset",
            sa.Enum(
                "contributions",
                "expenditures",
                "independent_expenditures",
                name="cf_dataset",
            ),
            nullable=False,
        ),
        sa.Column("download_id", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("content_disposition_filename", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column(
            "column_names", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "fetched", "quarantined", "loaded", "pruned", name="cf_snapshot_status"
            ),
            nullable=False,
        ),
        sa.Column("amount_sum", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column(
            "negative_amount_sum", sa.Numeric(precision=20, scale=4), nullable=True
        ),
        sa.Column("blank_date_count", sa.Integer(), nullable=True),
        sa.Column("distinct_row_count", sa.Integer(), nullable=True),
        sa.Column("distinct_filer_count", sa.Integer(), nullable=True),
        sa.Column(
            "rows_by_year", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "blank_counts_by_column",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("malformed_quote_record_count", sa.Integer(), nullable=True),
        sa.Column(
            "validation_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cf_snapshot")),
        sa.UniqueConstraint(
            "dataset", "content_hash", name=op.f("uq_cf_snapshot_dataset_content_hash")
        ),
        sa.UniqueConstraint("id", "dataset", name="uq_cf_snapshot_id_dataset"),
    )
    op.create_index(
        "ix_cf_snapshot_dataset_status",
        "cf_snapshot",
        ["dataset", "status"],
        unique=False,
    )
    op.create_table(
        "cf_fetch_observation",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column(
            "dataset",
            sa.Enum(
                "contributions",
                "expenditures",
                "independent_expenditures",
                name="cf_dataset",
            ),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column("download_id", sa.String(length=32), nullable=False),
        sa.Column("requested_url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "response_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("reused_existing_snapshot", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_run.id"],
            name=op.f("fk_cf_fetch_observation_ingestion_run_id_ingestion_run"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["cf_snapshot.id"],
            name=op.f("fk_cf_fetch_observation_snapshot_id_cf_snapshot"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cf_fetch_observation")),
    )
    op.create_index(
        "ix_cf_fetch_observation_dataset_started",
        "cf_fetch_observation",
        ["dataset", "started_at"],
        unique=False,
    )
    op.create_table(
        "cf_release",
        sa.Column("contributions_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("expenditures_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("independent_expenditures_snapshot_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("building", "published", "superseded", name="cf_release_status"),
            nullable=False,
        ),
        sa.Column("fetch_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetch_completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "contributions_dataset",
            sa.Enum(
                "contributions",
                "expenditures",
                "independent_expenditures",
                name="cf_dataset",
            ),
            sa.Computed("'contributions'", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "expenditures_dataset",
            sa.Enum(
                "contributions",
                "expenditures",
                "independent_expenditures",
                name="cf_dataset",
            ),
            sa.Computed("'expenditures'", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "independent_dataset",
            sa.Enum(
                "contributions",
                "expenditures",
                "independent_expenditures",
                name="cf_dataset",
            ),
            sa.Computed("'independent_expenditures'", persisted=True),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contributions_snapshot_id", "contributions_dataset"],
            ["cf_snapshot.id", "cf_snapshot.dataset"],
            name="fk_cf_release_contributions_snapshot",
        ),
        sa.ForeignKeyConstraint(
            ["expenditures_snapshot_id", "expenditures_dataset"],
            ["cf_snapshot.id", "cf_snapshot.dataset"],
            name="fk_cf_release_expenditures_snapshot",
        ),
        sa.ForeignKeyConstraint(
            ["independent_expenditures_snapshot_id", "independent_dataset"],
            ["cf_snapshot.id", "cf_snapshot.dataset"],
            name="fk_cf_release_independent_snapshot",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_run.id"],
            name=op.f("fk_cf_release_ingestion_run_id_ingestion_run"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cf_release")),
    )
    op.create_index("ix_cf_release_status", "cf_release", ["status"], unique=False)
    op.create_table(
        "cf_snapshot_body",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("compressed_hash", sa.String(length=64), nullable=False),
        sa.Column("compressed_byte_size", sa.BigInteger(), nullable=False),
        sa.Column("compression", sa.String(length=20), nullable=False),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["cf_snapshot.id"],
            name=op.f("fk_cf_snapshot_body_snapshot_id_cf_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_cf_snapshot_body")),
        sa.UniqueConstraint("object_key", name=op.f("uq_cf_snapshot_body_object_key")),
    )
    op.create_table(
        "cf_current_release",
        sa.Column("id", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id", name=op.f("ck_cf_current_release_single_row")),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["cf_release.id"],
            name=op.f("fk_cf_current_release_release_id_cf_release"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cf_current_release")),
    )


def downgrade() -> None:
    # Order matters: cf_current_release points at cf_release, cf_release's composite keys
    # point at cf_snapshot, and cf_snapshot_body cascades from it.
    op.drop_table("cf_current_release")
    op.drop_index("ix_cf_release_status", table_name="cf_release")
    op.drop_table("cf_release")
    op.drop_table("cf_snapshot_body")
    op.drop_index(
        "ix_cf_fetch_observation_dataset_started", table_name="cf_fetch_observation"
    )
    op.drop_table("cf_fetch_observation")
    op.drop_index("ix_cf_snapshot_dataset_status", table_name="cf_snapshot")
    op.drop_table("cf_snapshot")
    # The enum types outlive their tables, so a re-upgrade would fail on a name clash.
    for name in ("cf_release_status", "cf_snapshot_status", "cf_dataset"):
        postgresql.ENUM(name=name).drop(op.get_bind(), checkfirst=True)
